apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-sidd-cc
  namespace: homepage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: local-sidd-cc-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.siddhomelab.cc"
  dnsNames:
  - "siddhomelab.cc"
  - "*.siddhomelab.cc"