apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd

spec:
  project: default

  sources:
    # Helm chart source
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 61.3.2
      helm:
        valueFiles:
        - $values/gitops/platform/monitoring/values.yaml

    # Values repo
    - repoURL: https://github.com/SiddMallick/homelab-k3s
      targetRevision: master
      ref: values #Used as alias in the helm chart source

  destination:
    name: omen-k3s
    namespace: monitoring


# # If you want to auto-sync, uncomment this
  syncPolicy:
    automated:
      prune: true
      selfHeal: true