apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media-retain
provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
reclaimPolicy: Retain
parameters:
  archiveOnDelete: "true"
volumeBindingMode: Immediate