apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: deb-k3s-agent
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  finalizers:
  - kubernetes.io/pvc-protection
  name: jellyfin-config-pvc
  namespace: apps-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path-delete
