apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd

spec:
  project: default

  sources:
    # 🔹 Helm chart source
    - repoURL: https://jellyfin.github.io/jellyfin-helm
      chart: jellyfin
      targetRevision: 3.2.0
      helm:
        valueFiles:
        - $values/apps/jellyfin/values-dev.yaml

    - repoURL: https://github.com/SiddMallick/homelab-k3s
      targetRevision: master
      path: apps/jellyfin

    # 🔹 Values repo
    - repoURL: https://github.com/SiddMallick/homelab-k3s
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

  # syncPolicy:
  #   automated:
  #     prune: false
  #     selfHeal: false