apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://jellyfin.github.io/jellyfin-helm
    chart: jellyfin
    targetRevision: 3.2.0

  - repoURL: https://github.com/SiddMallick/homelab-k3s
    targetRevision: main
    ref: values


    helm:
      valueFiles:
        - jellyfin/values-dev.yaml
    
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  source:
    helm:
      valueFiles:
        - $values/jellyfin/values-dev.yaml