apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment | default "dev" }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      environment: {{ .Values.environment | default "dev" }}
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        environment: {{ .Values.environment | default "dev" }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}

        {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
            
        {{- with .Values.livenessProbe  }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.containerPort }}

      {{- with .Values.livenessProbe  }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
