apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefName }}
                  key: {{ .Values.secretRefKey }}

          command:
            - sh
            - -c
            - |
              redis-server \
              --appendonly yes \
              --maxmemory 128mb \
              --maxmemory-policy allkeys-lru \
              --requirepass "$REDIS_PASSWORD"

          ports:
            - containerPort: {{ .Values.containerPort | default 6379 }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          volumeMounts:
            - name: redis-storage
              mountPath: /data

          {{- with .Values.livenessProbe  }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}