# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: drawio
#   namespace: argocd

# spec:
#   project: default

#   sources:
#     # Values repo
#     - repoURL: https://github.com/SiddMallick/homelab-k3s
#       targetRevision: master
#       ref: values #Used as alias in the helm chart source

#     # Helm chart and certificate source
#     - repoURL: https://github.com/SiddMallick/homelab-k3s
#       path: gitops/apps/drawio
#       targetRevision: master
#       helm:
#         valueFiles:
#         - $values/gitops/apps/drawio/values-dev.yaml

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: apps-dev


# # # If you want to auto-sync, uncomment this
#   # syncPolicy:
#   #   syncOptions:
#   #     - CreateNamespace=true