apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-docs-dev
  namespace: argocd
  annotations:
    # Use the alias 'docs'
    argocd-image-updater.argoproj.io/image-list: docs=msiddhartha1600/docusaurus-homelab-docs
    argocd-image-updater.argoproj.io/docs.allow-tags: regexp:^[a-f0-9]{7,40}$
    argocd-image-updater.argoproj.io/docs.update-strategy: latest
    
    # Mapping to your Helm values
    argocd-image-updater.argoproj.io/docs.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/docs.helm.image-tag: image.tag
    
    # Corrected Write-Back Logic
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-homelab-repo
    # You MUST add this line because you have multiple sources
    argocd-image-updater.argoproj.io/write-back-repository: git
    argocd-image-updater.argoproj.io/git-branch: master
    # Note: This is specifically for Kustomize or Helm value updates
    argocd-image-updater.argoproj.io/write-back-target: "file:gitops/apps/homelab-docs/values-dev.yaml"
  
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: git@github.com:SiddMallick/homelab-k3s.git
    path: gitops/apps/homelab-docs
    targetRevision: master
    helm:
      valueFiles:
        - values-dev.yaml
  # sources:
    # - repoURL: git@github.com:SiddMallick/homelab-k3s.git
    #   targetRevision: master
    #   ref: values 

    # - repoURL: git@github.com:SiddMallick/homelab-k3s.git
    #   path: gitops/apps/homelab-docs
    #   targetRevision: master
    #   helm:
    #     valueFiles:
    #     - $values/gitops/apps/homelab-docs/values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: apps-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true