apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | default "homepage" }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}