apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | default "homepage" }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    environment: {{ .Values.environment }}
secrets:
  - name: {{ .Release.Name }}