apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | default "homepage" }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    environment: {{ .Values.environment }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}