helm:
  parameters:
  - name: image.repository
    value: msiddhartha1600/docusaurus-homelab-docs
    forcestring: true
  - name: image.tag
    value: a386d7a62e7b20337383caef47df534153583992
    forcestring: true
