helm:
  parameters:
  - name: image.repository
    value: msiddhartha1600/docusaurus-homelab-docs
    forcestring: true
  - name: image.tag
    value: bda3deb5ea6afcb4a85e45d072f8ff298aa40226
    forcestring: true
