helm:
  parameters:
  - name: image.repository
    value: msiddhartha1600/docusaurus-homelab-docs
    forcestring: true
  - name: image.tag
    value: e1e3ffdccda1c52227a912a777124415ff1c6402
    forcestring: true
